"""
Transparency label selector (M5).

Maps a combined confidence score to the final label and the verbatim,
human-facing transparency text. The three variants and their thresholds are
lifted directly from planning.md Section 3 ("Transparency Label Design") and
Section 2 ("Uncertainty Representation"):

    confidence >= 0.85   → high_confidence_ai      (Variant A)
    confidence <= 0.20   → high_confidence_human   (Variant B)
    else                 → uncertain               (Variant C)

Both threshold edges are inclusive, matching the score bands in Section 2
(0.85–1.00 high AI, 0.00–0.20 high human, 0.21–0.84 uncertain).

The text below is VERBATIM from planning.md Section 3 — do not paraphrase.
The label appears alongside the content on a creative-sharing platform, so
Variant C is deliberately protective ("has not been flagged"), never a hedged
accusation.
"""

# High-confidence AI threshold — kept high on purpose so it is hard to trigger.
# A false positive (human work flagged AI) harms a creator; the system accepts
# more false negatives in exchange (planning.md Section 2, asymmetric design).
HIGH_AI_THRESHOLD: float = 0.85
HIGH_HUMAN_THRESHOLD: float = 0.20

# Verbatim transparency text — Variants A / B / C from planning.md Section 3.
TRANSPARENCY_TEXT: dict[str, str] = {
    "high_confidence_ai": (
        "Our system has determined with high confidence that this content was "
        "generated by an AI writing tool. It has been labeled accordingly. "
        "If you are the creator and believe this is incorrect, you can submit "
        "an appeal below."
    ),
    "high_confidence_human": (
        "Our system has reviewed this content and found no significant indicators "
        "of AI generation. This work appears to be human-authored."
    ),
    "uncertain": (
        "Our system could not confidently determine the origin of this content. "
        "This work has not been flagged as AI-generated."
    ),
}


def get_label(confidence: float) -> dict:
    """
    Map a confidence score in [0.0, 1.0] to its transparency label.

    Args:
        confidence: Combined AI-probability score from the score combiner.

    Returns:
        {"label": str, "transparency_text": str} where ``label`` is one of
        ``high_confidence_ai`` | ``high_confidence_human`` | ``uncertain`` and
        ``transparency_text`` is the verbatim end-user copy for that band.
    """
    if confidence >= HIGH_AI_THRESHOLD:
        label = "high_confidence_ai"
    elif confidence <= HIGH_HUMAN_THRESHOLD:
        label = "high_confidence_human"
    else:
        label = "uncertain"

    return {"label": label, "transparency_text": TRANSPARENCY_TEXT[label]}
