"""
Transparency label tests (M5) — labels.get_label.

Locks the three variants and their thresholds to planning.md Section 3, with
the expected copy transcribed independently from the spec (not imported from
labels.py) so a silent edit to the label text is caught.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from labels import get_label

# Verbatim from planning.md Section 3.
VARIANT_A = (
    "Our system has determined with high confidence that this content was "
    "generated by an AI writing tool. It has been labeled accordingly. "
    "If you are the creator and believe this is incorrect, you can submit "
    "an appeal below."
)
VARIANT_B = (
    "Our system has reviewed this content and found no significant indicators "
    "of AI generation. This work appears to be human-authored."
)
VARIANT_C = (
    "Our system could not confidently determine the origin of this content. "
    "This work has not been flagged as AI-generated."
)


def test_variant_a_high_confidence_ai():
    for conf in (0.85, 0.91, 1.0):
        r = get_label(conf)
        assert r["label"] == "high_confidence_ai"
        assert r["transparency_text"] == VARIANT_A


def test_variant_b_high_confidence_human():
    for conf in (0.0, 0.10, 0.20):
        r = get_label(conf)
        assert r["label"] == "high_confidence_human"
        assert r["transparency_text"] == VARIANT_B


def test_variant_c_uncertain():
    for conf in (0.2001, 0.60, 0.8499):
        r = get_label(conf)
        assert r["label"] == "uncertain"
        assert r["transparency_text"] == VARIANT_C


def test_thresholds_are_inclusive_edges():
    # 0.85 -> AI (inclusive), just below -> uncertain
    assert get_label(0.85)["label"] == "high_confidence_ai"
    assert get_label(0.8499)["label"] == "uncertain"
    # 0.20 -> human (inclusive), just above -> uncertain
    assert get_label(0.20)["label"] == "high_confidence_human"
    assert get_label(0.2001)["label"] == "uncertain"


def test_return_shape():
    r = get_label(0.5)
    assert set(r.keys()) == {"label", "transparency_text"}
