"""
Signal 1 — Groq LLM Classification

Sends the submitted text to the Groq inference API with a structured prompt
that asks for a JSON-only response.  Retries up to 2 times on timeout or
transient error before marking the signal as failed.

Return contract (from planning.md Section 1):
    {
        "status":     "ok" | "failed",
        "label":      "ai_generated" | "human_written",   # only when ok
        "confidence": float 0.0–1.0,                      # only when ok
        "reasoning":  str,                                 # only when ok
    }

The confidence value is what the score combiner consumes.
"""

import os
import json
import time
import logging

from groq import Groq, APITimeoutError, APIStatusError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Prompt — instructs the model to return JSON only
# ---------------------------------------------------------------------------
SYSTEM_PROMPT = """\
You are an expert forensic writing analyst. Your task is to determine whether
a piece of text was written by a human or generated by an AI language model.

Respond with a JSON object only — no markdown, no explanation outside the JSON.
The JSON must have exactly these three keys:

{
  "label": "ai_generated" | "human_written",
  "confidence": <float between 0.0 and 1.0 — how confident you are in the label>,
  "reasoning": "<one or two sentences summarising the key signals you observed>"
}

For the confidence field:
  1.0 = absolutely certain
  0.5 = genuinely uncertain
  0.0 = the opposite label is almost certain

Err toward 0.5 when the signals are mixed rather than forcing a high-confidence verdict.
"""

USER_PROMPT_TEMPLATE = """\
Analyse the following text and return your JSON verdict:

---
{text}
---
"""

# ---------------------------------------------------------------------------
# Groq client — lazy-initialised so tests can import the module without a key
# ---------------------------------------------------------------------------
_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise EnvironmentError("GROQ_API_KEY environment variable is not set.")
        _client = Groq(api_key=api_key)
    return _client


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------
def classify(text: str, retries: int = 2, timeout: float = 5.0) -> dict:
    """
    Call the Groq API and return a structured classification result.

    Args:
        text:    The text to classify.
        retries: Number of retry attempts on timeout/transient failure.
        timeout: Per-attempt timeout in seconds.

    Returns:
        On success:
            {"status": "ok", "label": str, "confidence": float, "reasoning": str}
        On failure after all retries:
            {"status": "failed", "error": str}
    """
    client = _get_client()
    last_error: str = "unknown error"

    for attempt in range(retries + 1):
        try:
            response = client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": USER_PROMPT_TEMPLATE.format(text=text)},
                ],
                temperature=0.0,      # deterministic output
                max_tokens=256,
                timeout=timeout,
            )

            raw = response.choices[0].message.content.strip()
            parsed = _parse_response(raw)
            return {"status": "ok", **parsed}

        except APITimeoutError as exc:
            last_error = f"timeout on attempt {attempt + 1}: {exc}"
            logger.warning("Groq signal timeout (attempt %d/%d): %s", attempt + 1, retries + 1, exc)
            if attempt < retries:
                time.sleep(1.0)   # brief back-off before retry

        except APIStatusError as exc:
            last_error = f"API status error {exc.status_code}: {exc.message}"
            logger.error("Groq API error: %s", last_error)
            break   # non-transient; no point retrying

        except (ValueError, KeyError) as exc:
            last_error = f"response parse error: {exc}"
            logger.error("Groq signal parse error: %s", last_error)
            break

    return {"status": "failed", "error": last_error}


# ---------------------------------------------------------------------------
# Response parser
# ---------------------------------------------------------------------------
def _parse_response(raw: str) -> dict:
    """
    Parse the model's JSON response and validate required fields.

    Raises ValueError if the JSON is malformed or fields are missing/invalid.
    """
    # Strip accidental markdown fences the model might add
    if raw.startswith("```"):
        lines = raw.splitlines()
        raw = "\n".join(lines[1:-1] if lines[-1].strip() == "```" else lines[1:])

    data = json.loads(raw)   # raises json.JSONDecodeError → caught as ValueError above

    label = data.get("label")
    if label not in {"ai_generated", "human_written"}:
        raise ValueError(f"Unexpected label value: {label!r}")

    confidence = float(data.get("confidence", -1))
    if not (0.0 <= confidence <= 1.0):
        raise ValueError(f"Confidence out of range: {confidence}")

    reasoning = str(data.get("reasoning", ""))

    return {"label": label, "confidence": confidence, "reasoning": reasoning}


# ---------------------------------------------------------------------------
# Confidence cap
#
# llama-3.1-8b-instant is a weak, over-confident detector: calibration testing
# (see context_2.md) showed it returning 0.95 confidence on *every* sample —
# including text it labelled incorrectly. Since Groq carries the largest
# combiner weight (0.50, and 1.0 when it is the only active signal), an
# unchecked 0.95 lets a single confidently-wrong LLM verdict dominate the final
# score. We cap its effective confidence at 0.85: it can still reach the
# high-confidence boundary on its own, but can never push *past* it — so a
# second signal is always needed to move a verdict decisively, and a wrong Groq
# read is pulled toward the uncertain band rather than an extreme.
# ---------------------------------------------------------------------------
GROQ_CONFIDENCE_CAP = 0.85


def label_to_ai_probability(label: str, confidence: float) -> float:
    """
    Convert Groq's label + confidence into a single AI-probability float.

    Groq returns how confident it is in its own label — not in AI generation.
    This function normalises that into a value where:
        1.0 = certainly AI-generated
        0.0 = certainly human-written

    The model's stated confidence is first capped at GROQ_CONFIDENCE_CAP so a
    single over-confident LLM verdict cannot dominate the combined score.

    Examples (with cap = 0.85):
        label="ai_generated",  confidence=0.95 → 0.85  (capped strong AI signal)
        label="human_written", confidence=0.95 → 0.15  (capped strong human signal)
        label="ai_generated",  confidence=0.50 → 0.50  (uncertain either way)
    """
    capped = min(confidence, GROQ_CONFIDENCE_CAP)
    if label == "ai_generated":
        return capped              # already in AI-probability direction
    else:
        return 1.0 - capped        # invert: high confidence in human → low AI score
